
USE ROLE GG_SNOWFLAKE_REPORTING_GPAVON;
USE WAREHOUSE FRB_WH;
USE DATABASE EDCI_SANDBOX;
USE SCHEMA REPORTING_GPAVON;

/*
For every household under respective RM, return all client phone numbers and emails.

Note: 
1) This will exclude clients on accounts (i.e secondaries ) in which have no association with respective RM, either as the Customer or MHH officer. 
2) This will exclude accounts that have a closed status. 
*/


set LOGIN='ggooch';

/*Individuals can have other initials, like shared and team initials, we capture that here*/
with  ALL_INITIALS AS (
            SELECT
            DISTINCT MHH_OFCR_CD
            FROM EDCI_SANDBOX.REPORTING_GPAVON.ENGAGEMENT
            WHERE 1 = 1
            AND USER = $LOGIN
            AND INSERT_DT = (SELECT MAX(INSERT_DT)  FROM EDCI_SANDBOX.REPORTING_GPAVON.ENGAGEMENT WHERE USER = $LOGIN )

)




--GET EVERY CUSTOMER AND ALL ACCOUNTS THEY ARE ASSOCIATED WITH, THIS INCLUDES PRIMARIES AND SECONDARIES 
,TOTAL_POPULATION as (
SELECT
		  A.ACCT_NBR
		, A.SOURCE_CD
        , PROD.PRD_GRP
		, C.CDM_CUST_KEY
		, REPLACE(C.CUST_NM,'	',' ') AS CUST_NM
		,'Primary' REL_CD
	    , C.PERSON_ORG_FLG
		FROM CUSTDM.DBO.T_CDM_ACCT AS A

		LEFT JOIN CUSTDM.DBO.T_CDM_ACCT_FACT_CURR AS F
			ON A.CDM_ACCT_KEY = F.CDM_ACCT_KEY
		LEFT JOIN CUSTDM.DBO.T_CDM_CUST AS C
			ON F.CDM_CUST_KEY = C.CDM_CUST_KEY
        LEFT JOIN CUSTDM.DBO.T_CDM_PRODUCT PROD
            ON (PROD.DIM_PRODUCT_ID = F.DIM_PRODUCT_ID  AND PROD.CURR_REC_IND = 1)


  
		WHERE 1 = 1
		AND A.CURR_REC_IND = 1
		--AND A.ACCT_STAT_CD = 1
		AND C.CURR_REC_IND = 1

		UNION ALL
		-- SECONDARIES
		SELECT
		  A.ACCT_NBR
		, A.SOURCE_CD
        , PROD.PRD_GRP
		, AC.CDM_CUST_KEY ---
		, REPLACE(AC.CUST_NM,'	',' ') AS CUST_NM
		, RC.REL_CD_DESC
		, C.PERSON_ORG_FLG
		--INTO [DataScienceAndAnalytics].[BP].[Custs]
		FROM CUSTDM.DBO.T_CDM_ACCT AS A

		LEFT JOIN CUSTDM.DBO.T_CDM_ACCT_CUST AS AC
			ON (A.CDM_ACCT_KEY = AC.CDM_ACCT_KEY)

		LEFT JOIN CUSTDM.DBO.T_CDM_ACCT_FACT_CURR AS F
			ON A.CDM_ACCT_KEY = F.CDM_ACCT_KEY
		LEFT JOIN CUSTDM.DBO.T_CDM_CUST AS C
			ON F.CDM_CUST_KEY = C.CDM_CUST_KEY

		LEFT JOIN CUSTDM.DBO.T_CDM_REL_CD AS RC
			ON AC.CDM_REL_CD = RC.REL_CD
        
        LEFT JOIN CUSTDM.DBO.T_CDM_PRODUCT PROD
            ON (PROD.DIM_PRODUCT_ID = F.DIM_PRODUCT_ID  AND PROD.CURR_REC_IND = 1)

		WHERE 1 = 1
		AND A.CURR_REC_IND = 1
		--AND A.ACCT_STAT_CD = 1
		AND C.CURR_REC_IND = 1
)


--GRAB EVERY HOUSEHOLD, and ALL ACCOUNTS ASSOCIATED WITH THAT HOUSEHOLD except if the account status = closed
, HOUSEHOLD_AND_ALL_ACCTS AS (
  
                  SELECT * 
                  FROM (


                            SELECT 

                            DISTINCT PR.PARENT_CDM_CUST_KEY
                            ,ACCT.ACCT_NBR
                            ,PR.CUST_REL_NM AS HOUSEHOLD_NAME
                            ,PR.PRIME_CUST_REL_OFCR_CD MHH_OFCR_CD
                            ,CURR_BAL_AMT
                            ,IFNULL(MTD_AVG_BAL_AMT,0) MTD_AVG_BAL_AMT
                            ,ROW_NUMBER() OVER(PARTITION BY PR.PARENT_CDM_CUST_KEY, ACCT.ACCT_NBR ORDER BY ACCT.ACCT_NBR) AS DUPE_REMOVE -- BULLET PROOFING

                            FROM CustDM.DBO.T_CDM_ACCT_FACT_CURR FACT
                            LEFT JOIN CUSTDM.DBO.T_CDM_CUST_PRIMARY_REL PR
                                ON (PR.CHILD_CDM_CUST_KEY = FACT.CHILD_CDM_CUST_KEY)
                            LEFT JOIN CustDM.DBO.T_CDM_ACCT ACCT
                                ON (ACCT.CDM_ACCT_KEY = FACT.CDM_ACCT_KEY)
                            LEFT JOIN CUSTDM.DBO.T_CDM_ACCT_OFCR AS ACCT_OFCR
                                      ON (ACCT_OFCR.CDM_ACCT_KEY = FACT.CDM_ACCT_KEY)
                            LEFT JOIN (SELECT * FROM CUSTDM.DBO.T_CDM_INITIALS WHERE CURR_REC_IND = 1) AS INIT
                                      ON (ACCT_OFCR.DIM_INITIALS_ID = INIT.DIM_INITIALS_ID)
                            LEFT JOIN  CUSTDM.DBO.T_CDM_OFCR_TYPE AS OFCR_TYPE
                                      ON (ACCT_OFCR.CUST_OFCR_TYPE_ID = OFCR_TYPE.CUST_OFCR_TYPE_ID)
                            WHERE 1 = 1
                            AND INIT.INITIALS IS NOT NULL
                            AND PR.PARENT_CDM_CUST_KEY IS NOT NULL      
                            AND ACCT.ACCT_STAT <> 'Closed'

                     ) HOUSEHOLD_AND_ALL_ACCTS_INNER
                  WHERE 1 = 1 
                  AND DUPE_REMOVE = 1 
)

--FOR EVERY CUSTOMER FIND THEIR EMAIL :) 
,EMAILS AS (
                SELECT 
                 CDM_CUST_KEY
                ,EMAIL_TYP_CD
                ,EMAIL_SOURCE_CD
                ,EMAIL_ADDR
                FROM
                (
                      SELECT * 
                      -- FIRST FIND THE EMAIL THAT IS TAGGED AS PRIMARY, THEN SELECT THE LATEST EMAIL
                      ,ROW_NUMBER() OVER (PARTITION BY CDM_CUST_KEY 
                                          ORDER BY (
                                                    CASE
                                                        WHEN EMAIL_TYPE_DESC = 'Primary' THEN 1
                                                        WHEN EMAIL_TYPE_DESC = 'Alternate' THEN 2
                                                        ELSE 3
                                                    END 
                                                    ) ASC
                                                  ,EMAIL_CREATE_DT DESC
                                           ) AS LATEST_RECORD
                      FROM CUSTDM.ALLCLIENTS.V_CDM_CUST_EMAILS
                  ) CUSTOMER_EMAIL
                  WHERE 1 = 1 
                  AND LATEST_RECORD = 1 




)

--FOR EVERY CUSTOMER FIND THEIR PHONE NUMBERS
,PHONES AS (

   
          SELECT
          CDM_CUST_KEY

          ,MAX(CASE WHEN PHONE_TYPE = 1 AND PHONE_ORDER = 1 THEN PHONE_NBR END)  AS  "Home Phone (Main)"
          ,MAX(CASE WHEN PHONE_TYPE = 1 AND PHONE_ORDER = 2 THEN PHONE_NBR END)  AS  "Home Phone (Other)"
          ,MAX(CASE WHEN PHONE_TYPE = 2 AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS  "Business Phone (Main)"
          ,MAX(CASE WHEN PHONE_TYPE = 2 AND PHONE_ORDER = 2 THEN PHONE_NBR END ) AS  "Business Phone (Other)"
          ,MAX(CASE WHEN PHONE_TYPE = 3 AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Mobile Phone (Main)"
          ,MAX(CASE WHEN PHONE_TYPE = 3 AND PHONE_ORDER = 2 THEN PHONE_NBR END ) AS "Mobile Phone (Other)" 
          ,MAX(CASE WHEN PHONE_TYPE = 4	AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Fax Phone"
          ,MAX(CASE WHEN PHONE_TYPE = 5	AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Phone1 Phone"
          ,MAX(CASE WHEN PHONE_TYPE = 6	AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Phone 2 Phone"
          ,MAX(CASE WHEN PHONE_TYPE = 7	AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Telex Phone"
          ,MAX(CASE WHEN PHONE_TYPE = 8	AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Daytime Phone Phone"
          ,MAX(CASE WHEN PHONE_TYPE = 9	AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Pager Phone"
          ,MAX(CASE WHEN PHONE_TYPE = 10 AND PHONE_ORDER = 1 THEN PHONE_NBR END )  AS "MFA SMS PHONE Phone"
          ,MAX(CASE WHEN PHONE_TYPE = 11 AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "MFA VOICE PHONE Phone"
          ,MAX(CASE WHEN PHONE_TYPE = 12 AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Q2 BUSINESS PHONE Phone"
          ,MAX(CASE WHEN PHONE_TYPE > 12 AND PHONE_ORDER = 1 THEN PHONE_NBR END ) AS "Other Phone"
          FROM   (
                  SELECT CDM_CUST_KEY
                      , PHONE_NBR
                      , PHONE_TYPE
                      , OCCURANCE_COUNT
                      , ROW_NUMBER() OVER(PARTITION BY CDM_CUST_KEY, PHONE_TYPE ORDER BY OCCURANCE_COUNT DESC) AS PHONE_ORDER
                  FROM CustDM.dbo.T_CDM_CUST_PHONE
                  ) PHONES
          WHERE 1 = 1 

          GROUP BY CDM_CUST_KEY


)

,FINAL AS (

       SELECT 
       --MHH ASSOCIATED WITH OFFICER DETAILS
        CONCAT('=HYPERLINK("https://crb/Customer/',HOUSEHOLD_AND_ALL_ACCTS.PARENT_CDM_CUST_KEY,'","', CONCAT('https://crb/Customer/',HOUSEHOLD_AND_ALL_ACCTS.PARENT_CDM_CUST_KEY, '")')) AS HH_LINK 
       ,HOUSEHOLD_AND_ALL_ACCTS.PARENT_CDM_CUST_KEY
       ,HOUSEHOLD_AND_ALL_ACCTS.HOUSEHOLD_NAME
       ,HOUSEHOLD_AND_ALL_ACCTS.MHH_OFCR_CD
       ,HOUSEHOLD_AND_ALL_ACCTS.ACCT_NBR
       ,TP.PRD_GRP
       ,HOUSEHOLD_AND_ALL_ACCTS.CURR_BAL_AMT
       ,HOUSEHOLD_AND_ALL_ACCTS.MTD_AVG_BAL_AMT
       
       --ASSOCIATED CLIENT DETAILS, I.E IF THERE IS A SECONDARY ON AN ACCOUNT GET THEIR PARENT HH KEY, OFFICER, ETC...
       ,CONCAT('=HYPERLINK("https://crb/Customer/',TP.CDM_CUST_KEY,'","', CONCAT('https://crb/Customer/',TP.CDM_CUST_KEY, '")')) AS CLIENT_LINK 
       ,TP.CDM_CUST_KEY
       ,TP.CUST_NM
       ,CUST_OFFICER.CUST_FIRST_NM AS CLIENT_FIRST_NM-- ALBEIT CUST_OFFICER IS THE TABLE THIS WILL ALSO GIVE YOU THAT CUSTOMERS FIRST NAME
       ,CUST_OFFICER.CUST_LAST_NM AS CLIENT_LAST_NM  -- ALBEIT CUST_OFFICER IS THE TABLE THIS WILL ALSO GIVE YOU THAT CUSTOMERS LAST NAME
       ,TP.REL_CD
       ,TP.PERSON_ORG_FLG
       ,CUSTOMERS_REL.PARENT_CDM_CUST_KEY AS CLIENT_PARENT_CDM_CUST_KEY
       ,CUSTOMERS_REL.PRIME_CUST_REL_OFCR AS CLIENT_MHH_OFCR
       ,CUSTOMERS_REL.PRIME_CUST_REL_OFCR_CD AS CLIENT_MHH_OFCR_CD
       ,CUST_OFFICER.PRIME_CUST_OFCR AS CLIENT_CUST_OFCR
       ,CUST_OFFICER.PRIME_CUST_OFCR_CD AS CLIENT_CUST_OFCR_CD
       
       ,CASE 
            WHEN TP.REL_CD = 'PRIMARY' AND CUSTOMERS_REL.PARENT_CDM_CUST_KEY <> HOUSEHOLD_AND_ALL_ACCTS.PARENT_CDM_CUST_KEY THEN 1 
            ELSE 0
        END AS ACCT_OWNER_NOT_IN_HH--THIS WILL CHECK IF THERE IS AN ACCOUNT IN THE HOUSEHOLD OWNED(CLIENT = PRIMARY) BY SOMEONE WHO DOES NOT BELONG TO THE HOUSEHOLD IN WHICH THE ACCOUNT RESIDES IN
        
        ,EMAILS.EMAIL_ADDR AS EMAIL
        ,PHONES."HOME PHONE (MAIN)"
        ,PHONES."HOME PHONE (OTHER)"
        ,PHONES."BUSINESS PHONE (MAIN)"
        ,PHONES."BUSINESS PHONE (OTHER)"
        ,PHONES."MOBILE PHONE (MAIN)"
        ,PHONES."MOBILE PHONE (OTHER)"
        ,PHONES."FAX PHONE"
        ,PHONES."PHONE1 PHONE"
        ,PHONES."PHONE 2 PHONE"
        ,PHONES."TELEX PHONE"
        ,PHONES."DAYTIME PHONE PHONE"
        ,PHONES."PAGER PHONE"
        ,PHONES."MFA SMS PHONE PHONE"
        ,PHONES."MFA VOICE PHONE PHONE"
        ,PHONES."Q2 BUSINESS PHONE PHONE"
        ,PHONES."OTHER PHONE"
        
        FROM  HOUSEHOLD_AND_ALL_ACCTS -- FOR EVERY HOUSEHOLD GET ALL ASSOCIATED ACCOUNTS 
        LEFT JOIN TOTAL_POPULATION TP -- FOR EVERY ACCOUNT GET ALL ASSOCIATED CLIENTS
            ON (TP.ACCT_NBR = HOUSEHOLD_AND_ALL_ACCTS.ACCT_NBR)
        LEFT JOIN CUSTDM.DBO.T_CDM_CUST_PRIMARY_REL CUSTOMERS_REL -- FOR EVERY CLIENT ASSOCIATED WITH AN ACCOUNT GET THEIR RESPECTIVE PARENT_CDM_CUST_KEY
            ON (TP.CDM_CUST_KEY = CUSTOMERS_REL.CHILD_CDM_CUST_KEY)
        LEFT JOIN CUSTDM.DBO.T_CDM_CUST CUST_OFFICER -- FOR EVERY CLIENT ASSOCIATED WITH AN ACCOUNT GET THEIR CUSTOMER OFFICER
            ON (TP.CDM_CUST_KEY = CUST_OFFICER.CDM_CUST_KEY )
        LEFT JOIN PHONES 
            ON (TP.CDM_CUST_KEY = PHONES.CDM_CUST_KEY)
        LEFT JOIN EMAILS
            ON (TP.CDM_CUST_KEY = EMAILS.CDM_CUST_KEY)
        WHERE 1 = 1
       -- AND HOUSEHOLD_AND_ALL_ACCTS.PARENT_CDM_CUST_KEY = '1000697892'
        and MHH_OFCR_CD IN (SELECT * FROM ALL_INITIALS)
      
        ORDER BY HOUSEHOLD_AND_ALL_ACCTS.PARENT_CDM_CUST_KEY, HOUSEHOLD_AND_ALL_ACCTS.ACCT_NBR 


)





SELECT 
DISTINCT HH_LINK
,PARENT_CDM_CUST_KEY
,HOUSEHOLD_NAME
,MHH_OFCR_CD
,REQUESTS.REQUESTED_INITIAL
,CONCAT(INIT.PREFERREDNAME,' ', INIT.LASTNAME) AS REQUESTED_NAME
,CLIENT_LINK
,CUST_NM
,CLIENT_FIRST_NM
,CLIENT_LAST_NM
,CLIENT_PARENT_CDM_CUST_KEY
,CLIENT_MHH_OFCR
,CLIENT_CUST_OFCR
,ACCT_OWNER_NOT_IN_HH
,EMAIL
,"HOME PHONE (MAIN)"
,"HOME PHONE (OTHER)"
,"BUSINESS PHONE (MAIN)"
,"BUSINESS PHONE (OTHER)"
,"MOBILE PHONE (MAIN)"
,"MOBILE PHONE (OTHER)"
,"FAX PHONE"
,"PHONE1 PHONE"
,"PHONE 2 PHONE"
,"TELEX PHONE"
,"DAYTIME PHONE PHONE"
,"PAGER PHONE"
,"MFA SMS PHONE PHONE"
,"MFA VOICE PHONE PHONE"
,"Q2 BUSINESS PHONE PHONE"
,"OTHER PHONE"
,IFNULL(JUST_FOR_ORDERING.RELATIVE_TOTAL_SCORE,0) RELATIVE_TOTAL_SCORE
,IFNULL(JUST_FOR_ORDERING.MONTHLYMONETARYVALUE,0) MONTHLYMONETARYVALUE
FROM FINAL A
LEFT JOIN (
                SELECT 
                 CRB_MHH_KEY
                , RELATIVE_TOTAL_SCORE
                , MONTHLYMONETARYVALUE
          
                FROM  EDCI_SANDBOX.REPORTING_GPAVON.ENGAGEMENT
                WHERE 1 = 1 
                AND USER =  $LOGIN
                AND INSERT_DT = (SELECT MAX(INSERT_DT) FROM  EDCI_SANDBOX.REPORTING_GPAVON.ENGAGEMENT WHERE USER = $LOGIN)
                AND MONTH_END = (SELECT MAX(MONTH_END) FROM EDCI_SANDBOX.REPORTING_GPAVON.ENGAGEMENT )

) JUST_FOR_ORDERING
ON (A.PARENT_CDM_CUST_KEY = JUST_FOR_ORDERING.CRB_MHH_KEY)
LEFT JOIN  EDCI_SANDBOX.REPORTING_GPAVON.REASSIGNMENT_REQUESTS REQUESTS
    ON (REQUESTS.MHH_KEY = A.PARENT_CDM_CUST_KEY)   
LEFT JOIN  (SELECT * FROM EagleVision.dbo.T_REF_PEOPLE_INITIALS WHERE CURRENTFLAG=1)  INIT
    ON (INIT.INITIALS = REQUESTS.REQUESTED_INITIAL )

WHERE 1 = 1 
/*EXCLUDE SECONDARIES THAT ARE NOT ASSOCAITED WITH HOUSEHOLD RM.
FOR EXAMPLE, IF WE HAVE A SECONDARY ON AN ACCOUNT AND THEIR OWN RESPECTIVE MHH IS ADAM,
BUT THE ACCOUNT WHICH SECODARY IS ASSOCIATED WITH IS UNDER A HOUSEHOLD IN WHICH ADAM IS NOT THE MHH OFFICER/CUST OFFICER - EXCLUDE THOSE CLIENTS*/
AND CLIENT_MHH_OFCR_CD IN (SELECT * FROM ALL_INITIALS) -- EXCLUDE CLIENT WHERE THEIR MHH OFFICER IS NOT HH MHH
AND CLIENT_CUST_OFCR_CD IN (SELECT * FROM ALL_INITIALS)-- EXCLUDE CLIENT WHERE THEIR CUSTOMER OFFICER  IS NOT HH MHH

ORDER BY IFNULL(JUST_FOR_ORDERING.RELATIVE_TOTAL_SCORE,0) DESC, IFNULL(JUST_FOR_ORDERING.MONTHLYMONETARYVALUE,0) DESC 




