USE ROLE GG_SNOWFLAKE_REPORTING_GPAVON;
USE WAREHOUSE FRB_WH;
USE DATABASE EDCI_SANDBOX;
USE SCHEMA REPORTING_GPAVON;


SET Curr = (select to_number(to_char(DATEADD(Day ,-1, current_date),'YYYYMMDD'),'99999999') );
select $Curr
